const CONSTANTS = {
  VERSION: "0.0.1",
  BACKGROUND_COLOR: "#96a9c1",
  BACKGROUND_COLOR_DARKEN_ALPHA: 0.7,
  BACKGROUND_COLOR_DARKEN_ALPHA_MAX: 0.7,
  DEBUG: false,
  CUTSCENE_SPEED_MULTIPLIER: 1,
  playerMaxLives: 3,
  DRAW_HITBOXES: true,
  DRAW_HURTBOXES: true,
  SPEEDY_MODE: false
};
