<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.11" tiledversion="1.11.2" name="CowboyTilemap" tilewidth="8" tileheight="8" tilecount="4000" columns="40">
 <image source="CowboyTilemap.png" width="320" height="800"/>
 <tile id="6" type="wall"/>
 <tile id="7" type="wall"/>
 <tile id="8" type="wall"/>
 <tile id="9" type="wall"/>
 <tile id="10" type="wall"/>
 <tile id="11" type="wall"/>
 <tile id="12" type="wall"/>
 <tile id="13" type="wall"/>
 <tile id="46" type="wall"/>
 <tile id="47" type="wall"/>
 <tile id="62" type="wall"/>
 <tile id="63" type="wall"/>
 <tile id="90" type="onewaywall"/>
 <tile id="91" type="onewaywall"/>
 <tile id="93" type="wall"/>
 <tile id="102" type="wall"/>
 <tile id="103" type="wall"/>
 <tile id="142" type="wall"/>
 <tile id="143" type="wall"/>
 <tile id="168" type="wall"/>
 <tile id="201" type="wall"/>
 <tile id="202" type="wall"/>
 <tile id="204" type="onewaywall"/>
 <tile id="281" type="wall"/>
 <tile id="320" type="wall"/>
 <tile id="321" type="wall"/>
 <tile id="322" type="wall"/>
 <tile id="323" type="wall"/>
 <tile id="324" type="onewaywall"/>
 <tile id="325" type="onewaywall"/>
 <tile id="326" type="wall"/>
 <tile id="327" type="wall"/>
 <tile id="328" type="wall"/>
 <tile id="329" type="wall"/>
 <tile id="330" type="wall"/>
 <tile id="331" type="wall"/>
 <tile id="338" type="onewaywall"/>
 <tile id="339" type="onewaywall"/>
 <tile id="340" type="onewaywall"/>
 <tile id="341" type="onewaywall"/>
 <tile id="342" type="onewaywall"/>
 <tile id="343" type="onewaywall"/>
 <tile id="345" type="wall"/>
 <tile id="346" type="wall"/>
 <tile id="347" type="wall"/>
 <tile id="351" type="onewaywall"/>
 <tile id="352" type="onewaywall"/>
 <tile id="353" type="onewaywall"/>
 <tile id="360" type="wall"/>
 <tile id="361" type="wall"/>
 <tile id="362" type="wall"/>
 <tile id="363" type="wall"/>
 <tile id="366" type="wall"/>
 <tile id="367" type="wall"/>
 <tile id="368" type="wall"/>
 <tile id="369" type="wall"/>
 <tile id="370" type="wall"/>
 <tile id="371" type="wall"/>
 <tile id="378" type="wall"/>
 <tile id="383" type="wall"/>
 <tile id="385" type="wall"/>
 <tile id="386" type="wall"/>
 <tile id="387" type="wall"/>
 <tile id="388" type="wall"/>
 <tile id="390" type="wall"/>
 <tile id="391" type="wall"/>
 <tile id="392" type="wall"/>
 <tile id="393" type="wall"/>
 <tile id="402" type="wall"/>
 <tile id="403" type="wall"/>
 <tile id="406" type="wall"/>
 <tile id="407" type="wall"/>
 <tile id="408" type="wall"/>
 <tile id="409" type="wall"/>
 <tile id="410" type="wall"/>
 <tile id="411" type="wall"/>
 <tile id="418" type="wall"/>
 <tile id="423" type="wall"/>
 <tile id="425" type="wall"/>
 <tile id="426" type="wall"/>
 <tile id="427" type="wall"/>
 <tile id="428" type="wall"/>
 <tile id="430" type="wall"/>
 <tile id="442" type="wall"/>
 <tile id="443" type="wall"/>
 <tile id="446" type="wall"/>
 <tile id="447" type="wall"/>
 <tile id="448" type="wall"/>
 <tile id="449" type="wall"/>
 <tile id="450" type="wall"/>
 <tile id="451" type="wall"/>
 <tile id="486" type="wall"/>
 <tile id="487" type="wall"/>
 <tile id="488" type="wall"/>
 <tile id="489" type="wall"/>
 <tile id="490" type="wall"/>
 <tile id="491" type="wall"/>
 <tile id="526" type="wall"/>
 <tile id="527" type="wall"/>
 <tile id="528" type="wall"/>
 <tile id="529" type="wall"/>
 <tile id="530" type="wall"/>
 <tile id="531" type="wall"/>
 <tile id="720" type="wall"/>
 <tile id="721" type="wall"/>
 <tile id="722" type="wall"/>
 <tile id="723" type="wall"/>
 <tile id="724" type="onewaywall"/>
 <tile id="725" type="onewaywall"/>
 <tile id="726" type="onewaywall"/>
 <tile id="727" type="onewaywall"/>
 <tile id="728" type="onewaywall"/>
 <tile id="729" type="onewaywall"/>
 <tile id="730" type="onewaywall"/>
 <tile id="731" type="onewaywall"/>
 <tile id="760" type="wall"/>
 <tile id="761" type="wall"/>
 <tile id="762" type="wall"/>
 <tile id="763" type="wall"/>
 <tile id="800" type="wall"/>
 <tile id="801" type="wall"/>
 <tile id="802" type="wall"/>
 <tile id="803" type="wall"/>
 <tile id="840" type="wall"/>
 <tile id="841" type="wall"/>
 <tile id="842" type="wall"/>
 <tile id="1144" type="wall"/>
 <tile id="1145" type="wall"/>
 <tile id="1146" type="wall"/>
 <tile id="1147" type="wall"/>
 <tile id="1175" type="onewaywall"/>
 <tile id="1176" type="onewaywall"/>
 <tile id="1178" type="onewaywall"/>
 <tile id="1179" type="onewaywall"/>
 <tile id="1181" type="onewaywall"/>
 <tile id="1182" type="onewaywall"/>
 <tile id="1184" type="wall"/>
 <tile id="1185" type="wall"/>
 <tile id="1186" type="wall"/>
 <tile id="1187" type="wall"/>
 <tile id="1264" type="wall"/>
 <tile id="1265" type="wall"/>
 <tile id="1266" type="wall"/>
 <tile id="1267" type="wall"/>
 <tile id="1304" type="wall"/>
 <tile id="1305" type="wall"/>
 <tile id="1306" type="wall"/>
 <tile id="1307" type="wall"/>
</tileset>
