<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.11" tiledversion="1.11.2" name="GameJamSpriteSheet" tilewidth="8" tileheight="8" tilecount="800" columns="40">
 <image source="GameJamSpriteSheet.png" width="320" height="160"/>
 <tile id="0" type="wall"/>
 <tile id="1" type="wall"/>
 <tile id="2" type="wall"/>
 <tile id="3" type="wall"/>
 <tile id="9" type="wall"/>
 <tile id="10" type="wall"/>
 <tile id="11" type="wall"/>
 <tile id="12" type="wall"/>
 <tile id="18" type="wall"/>
 <tile id="19" type="wall"/>
 <tile id="20" type="wall"/>
 <tile id="21" type="wall"/>
 <tile id="40" type="wall"/>
 <tile id="41" type="wall"/>
 <tile id="42" type="wall"/>
 <tile id="43" type="wall"/>
 <tile id="49" type="wall"/>
 <tile id="50" type="wall"/>
 <tile id="51" type="wall"/>
 <tile id="52" type="wall"/>
 <tile id="58" type="wall"/>
 <tile id="59" type="wall"/>
 <tile id="60" type="wall"/>
 <tile id="61" type="wall"/>
 <tile id="80" type="wall"/>
 <tile id="81" type="wall"/>
 <tile id="82" type="wall"/>
 <tile id="83" type="wall"/>
 <tile id="89" type="wall"/>
 <tile id="90" type="wall"/>
 <tile id="91" type="wall"/>
 <tile id="92" type="wall"/>
 <tile id="98" type="wall"/>
 <tile id="99" type="wall"/>
 <tile id="100" type="wall"/>
 <tile id="101" type="wall"/>
 <tile id="120" type="wall"/>
 <tile id="121" type="wall"/>
 <tile id="122" type="wall"/>
 <tile id="126" type="damage"/>
 <tile id="129" type="wall"/>
 <tile id="130" type="wall"/>
 <tile id="131" type="wall"/>
 <tile id="135" type="damage"/>
 <tile id="138" type="wall"/>
 <tile id="139" type="wall"/>
 <tile id="140" type="wall"/>
 <tile id="144" type="damage"/>
</tileset>
