<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.10.1" name="tower-tileset" tilewidth="8" tileheight="8" tilecount="256" columns="16">
 <image source="../new-tiles.png" width="128" height="128"/>
 <tile id="0" type="wall"/>
 <tile id="1" type="wall"/>
 <tile id="2" type="wall"/>
 <tile id="3" type="wall"/>
 <tile id="4" type="wall"/>
 <tile id="5" type="wall"/>
 <tile id="7" type="wall"/>
 <tile id="8" type="wall"/>
 <tile id="9" type="wall"/>
 <tile id="10" type="wall"/>
 <tile id="11" type="wall"/>
 <tile id="21" type="damage"/>
 <tile id="37" type="checkpoint"/>
 <tile id="39" type="wall"/>
 <tile id="40" type="wall"/>
 <tile id="41" type="wall"/>
 <tile id="42" type="wall"/>
 <tile id="43" type="wall"/>
 <tile id="70" type="wall"/>
 <tile id="71" type="wall"/>
 <tile id="72" type="wall"/>
 <tile id="73" type="wall"/>
 <tile id="74" type="wall"/>
 <tile id="75" type="wall"/>
 <tile id="101" type="wall"/>
 <tile id="102" type="wall"/>
 <tile id="103" type="wall"/>
 <tile id="104" type="wall"/>
 <tile id="105" type="wall"/>
 <tile id="106" type="wall"/>
 <tile id="107" type="wall"/>
 <tile id="115" type="damage"/>
 <tile id="116" type="damage"/>
 <tile id="117" type="damage"/>
 <tile id="118" type="damage"/>
 <tile id="120" type="damage"/>
 <tile id="121" type="damage"/>
 <tile id="134" type="wall"/>
 <tile id="135" type="wall"/>
 <tile id="136" type="wall"/>
 <tile id="137" type="wall"/>
 <tile id="138" type="wall"/>
 <tile id="139" type="wall"/>
</tileset>
